name: fake_store_get_request
description: "Un pacquete que permite hacer una petición a la API fakestore para obtener una lista de productos"
version: 0.0.1
homepage: https://github.com/Marisolperez22/fake_store_get_request

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  build_runner: ^2.5.4
  flutter:
    sdk: flutter
  http: ^1.4.0
  mockito: ^5.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0





flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
