// Mocks generated by Mockito 5.4.6 from annotations
// in fake_store_get_request/test/services/fake_store_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:either_dart/either.dart' as _i5;
import 'package:fake_store_get_request/core/errors/failures.dart' as _i6;
import 'package:fake_store_get_request/data/models/cart.dart' as _i15;
import 'package:fake_store_get_request/data/models/login_response.dart' as _i11;
import 'package:fake_store_get_request/data/models/product.dart' as _i7;
import 'package:fake_store_get_request/domain/repositories/fake_store_repository.dart'
    as _i2;
import 'package:fake_store_get_request/domain/usecases/get_categories.dart'
    as _i12;
import 'package:fake_store_get_request/domain/usecases/get_product_by_category.dart'
    as _i13;
import 'package:fake_store_get_request/domain/usecases/get_product_detail.dart'
    as _i9;
import 'package:fake_store_get_request/domain/usecases/get_products.dart'
    as _i3;
import 'package:fake_store_get_request/domain/usecases/get_user_cart.dart'
    as _i14;
import 'package:fake_store_get_request/domain/usecases/login.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFakeStoreRepository_0 extends _i1.SmartFake
    implements _i2.FakeStoreRepository {
  _FakeFakeStoreRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetProducts].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProducts extends _i1.Mock implements _i3.GetProducts {
  MockGetProducts() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FakeStoreRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFakeStoreRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FakeStoreRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i7.Product>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, List<_i7.Product>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i7.Product>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i7.Product>>>);
}

/// A class which mocks [GetProductDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductDetail extends _i1.Mock implements _i9.GetProductDetail {
  MockGetProductDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FakeStoreRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFakeStoreRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FakeStoreRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Product>> call(int? idProduct) =>
      (super.noSuchMethod(
            Invocation.method(#call, [idProduct]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, _i7.Product>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, _i7.Product>>(
                this,
                Invocation.method(#call, [idProduct]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.Product>>);
}

/// A class which mocks [Login].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogin extends _i1.Mock implements _i10.Login {
  MockLogin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FakeStoreRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFakeStoreRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FakeStoreRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i11.LoginResponse>> call(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [username, password]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, _i11.LoginResponse>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, _i11.LoginResponse>>(
                    this,
                    Invocation.method(#call, [username, password]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i11.LoginResponse>>);
}

/// A class which mocks [GetCategories].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategories extends _i1.Mock implements _i12.GetCategories {
  MockGetCategories() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FakeStoreRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFakeStoreRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FakeStoreRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<String>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, List<String>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<String>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<String>>>);
}

/// A class which mocks [GetProductByCategory].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductByCategory extends _i1.Mock
    implements _i13.GetProductByCategory {
  MockGetProductByCategory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FakeStoreRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFakeStoreRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FakeStoreRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i7.Product>>> call(
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [category]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, List<_i7.Product>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i7.Product>>>(
                    this,
                    Invocation.method(#call, [category]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i7.Product>>>);
}

/// A class which mocks [GetUserCart].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserCart extends _i1.Mock implements _i14.GetUserCart {
  MockGetUserCart() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FakeStoreRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFakeStoreRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FakeStoreRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i15.Cart>> call(int? idUser) =>
      (super.noSuchMethod(
            Invocation.method(#call, [idUser]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, _i15.Cart>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, _i15.Cart>>(
                this,
                Invocation.method(#call, [idUser]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i15.Cart>>);
}
