// Mocks generated by Mockito 5.4.6 from annotations
// in fake_store_get_request/test/domain/usecases/get_product_by_category_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:fake_store_get_request/core/errors/failures.dart' as _i5;
import 'package:fake_store_get_request/data/models/cart.dart' as _i8;
import 'package:fake_store_get_request/data/models/login_response.dart' as _i9;
import 'package:fake_store_get_request/data/models/product.dart' as _i7;
import 'package:fake_store_get_request/domain/repositories/fake_store_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FakeStoreRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFakeStoreRepository extends _i1.Mock
    implements _i2.FakeStoreRepository {
  @override
  _i3.Future<_i4.Either<_i5.Failure, List<String>>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<String>>>.value(
                  _i6.dummyValue<_i4.Either<_i5.Failure, List<String>>>(
                    this,
                    Invocation.method(#getCategories, []),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, List<String>>>.value(
                  _i6.dummyValue<_i4.Either<_i5.Failure, List<String>>>(
                    this,
                    Invocation.method(#getCategories, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<String>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i7.Product>>> getProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i7.Product>>>.value(
                  _i6.dummyValue<_i4.Either<_i5.Failure, List<_i7.Product>>>(
                    this,
                    Invocation.method(#getProducts, []),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, List<_i7.Product>>>.value(
                  _i6.dummyValue<_i4.Either<_i5.Failure, List<_i7.Product>>>(
                    this,
                    Invocation.method(#getProducts, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i7.Product>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i7.Product>> getProductDetail(
    int? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductDetail, [productId]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i7.Product>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, _i7.Product>>(
                this,
                Invocation.method(#getProductDetail, [productId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, _i7.Product>>.value(
                  _i6.dummyValue<_i4.Either<_i5.Failure, _i7.Product>>(
                    this,
                    Invocation.method(#getProductDetail, [productId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i7.Product>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i8.Cart>> getUserCart(int? idUser) =>
      (super.noSuchMethod(
            Invocation.method(#getUserCart, [idUser]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i8.Cart>>.value(
              _i6.dummyValue<_i4.Either<_i5.Failure, _i8.Cart>>(
                this,
                Invocation.method(#getUserCart, [idUser]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, _i8.Cart>>.value(
                  _i6.dummyValue<_i4.Either<_i5.Failure, _i8.Cart>>(
                    this,
                    Invocation.method(#getUserCart, [idUser]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i8.Cart>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i7.Product>>> getProductByCategory(
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductByCategory, [category]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i7.Product>>>.value(
                  _i6.dummyValue<_i4.Either<_i5.Failure, List<_i7.Product>>>(
                    this,
                    Invocation.method(#getProductByCategory, [category]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, List<_i7.Product>>>.value(
                  _i6.dummyValue<_i4.Either<_i5.Failure, List<_i7.Product>>>(
                    this,
                    Invocation.method(#getProductByCategory, [category]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i7.Product>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i9.LoginResponse>> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i9.LoginResponse>>.value(
                  _i6.dummyValue<_i4.Either<_i5.Failure, _i9.LoginResponse>>(
                    this,
                    Invocation.method(#login, [username, password]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, _i9.LoginResponse>>.value(
                  _i6.dummyValue<_i4.Either<_i5.Failure, _i9.LoginResponse>>(
                    this,
                    Invocation.method(#login, [username, password]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i9.LoginResponse>>);
}
